# Generated by Django 5.2 on 2025-05-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_customuser_email_verified'),
    ]

    operations = [
    ]
