# Generated by Django 5.2 on 2025-05-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20250531_0002'),
    ]

    operations = [
    ]
