# Generated by Django 5.2 on 2025-05-30 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20250531_0120'),
    ]

    operations = [
    ]
